#!/usr/bin/env bash
# Local resolver for the demo domains: *.DOMAIN and *.127-0-0-1.nip.io -> 127.0.0.1, also offline.
#   scripts/dns.sh setup   dnsmasq as a launchd agent (user, port 53535) + /etc/resolver/<domain> (sudo once)
#   scripts/dns.sh check   checks agent, dnsmasq and macOS resolution
#   scripts/dns.sh remove  removes the agent and only our own resolver files (sudo)
#   scripts/dns.sh public  public A records -> 127.0.0.1 in Cloud DNS (convenience for Macs without a local resolver)
# dnsmasq runs without root privileges; sudo is needed only for writing to /etc/resolver.
set -euo pipefail

# shellcheck source=secrets.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/secrets.sh"

DNS_PORT=53535
DNS_LABEL="io.cf-kind-demo.dnsmasq"
RESOLVER_MARKER="# managed by cf-kind-demo"
RESOLVER_DIR="${RESOLVER_DIR:-/etc/resolver}"
LAUNCH_AGENT="$HOME/Library/LaunchAgents/$DNS_LABEL.plist"

render_dnsmasq_conf() {
  printf '%s\n' \
    "$RESOLVER_MARKER — do not edit by hand, generated by 'make dns'" \
    "port=$DNS_PORT" \
    "listen-address=127.0.0.1" \
    "bind-interfaces" \
    "no-resolv" \
    "no-hosts" \
    "no-poll" \
    "pid-file="
  local d
  for d in "$@"; do printf 'address=/%s/127.0.0.1\n' "$d"; done
}

render_resolver() {
  printf '%s\nnameserver 127.0.0.1\nport %s\n' "$RESOLVER_MARKER" "$DNS_PORT"
}

render_launchd_plist() {
  local bin="$1" conf="$2"
  cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$DNS_LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$bin</string>
    <string>--keep-in-foreground</string>
    <string>--conf-file=$conf</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
</dict>
</plist>
EOF
}

is_managed_resolver() {
  [[ -f "$1" ]] && head -1 "$1" | grep -qF "$RESOLVER_MARKER"
}

# resolver_plan DOMAIN… -> one line per domain: "skip|write|conflict <domain>"
resolver_plan() {
  local d f
  for d in "$@"; do
    f="$RESOLVER_DIR/$d"
    if [[ ! -e "$f" ]]; then echo "write $d"
    elif ! is_managed_resolver "$f"; then echo "conflict $d"
    elif [[ "$(cat "$f")" == "$(render_resolver)" ]]; then echo "skip $d"
    else echo "write $d"; fi
  done
}

dnsmasq_bin() {
  local b
  b="$(brew --prefix 2>/dev/null)/sbin/dnsmasq"
  [[ -x "$b" ]] || b="$(command -v dnsmasq || true)"
  [[ -x "$b" ]] || die "dnsmasq not found" "run: make prereqs"
  echo "$b"
}

install_agent() {
  local conf="$CFKD_HOME/dnsmasq.conf" bin
  bin="$(dnsmasq_bin)"
  mkdir -p "$CFKD_HOME" "$(dirname "$LAUNCH_AGENT")"
  chmod 700 "$CFKD_HOME"
  # shellcheck disable=SC2086
  render_dnsmasq_conf $RESOLVER_DOMAINS > "$conf"
  "$bin" --test --conf-file="$conf" >/dev/null 2>&1 || die "dnsmasq configuration invalid: $conf"
  render_launchd_plist "$bin" "$conf" > "$LAUNCH_AGENT"
  launchctl bootout "gui/$(id -u)/$DNS_LABEL" >/dev/null 2>&1 || true
  launchctl bootstrap "gui/$(id -u)" "$LAUNCH_AGENT"
  log_ok "dnsmasq agent running ($DNS_LABEL, 127.0.0.1:$DNS_PORT) for: $RESOLVER_DOMAINS"
}

install_resolvers() {
  local action d tmp writes=""
  # shellcheck disable=SC2086
  while read -r action d; do
    case "$action" in
      conflict) die "$RESOLVER_DIR/$d exists and does not belong to cf-kind-demo" "inspect the file; if needed choose another DOMAIN (make configure DOMAIN=…)" ;;
      write) writes="$writes $d" ;;
      skip) log_ok "$RESOLVER_DIR/$d is up to date" ;;
    esac
  done < <(resolver_plan $RESOLVER_DOMAINS)
  [[ -z "$writes" ]] && return 0

  log_info "writing$writes to $RESOLVER_DIR/ — this needs the sudo password once."
  tmp="$(mktemp)"
  render_resolver > "$tmp"
  sudo mkdir -p "$RESOLVER_DIR"
  for d in $writes; do sudo install -m 0644 "$tmp" "$RESOLVER_DIR/$d"; done
  rm -f "$tmp"
  sudo dscacheutil -flushcache
  sudo killall -HUP mDNSResponder 2>/dev/null || true
  log_ok "resolver files written:$writes"
}

# macOS resolution (not dig — dig ignores /etc/resolver)
resolves_to_loopback() {
  dscacheutil -q host -a name "$1" 2>/dev/null | grep -q '^ip_address: 127\.0\.0\.1$'
}

cmd_check() {
  load_config
  local failed=0 d
  if launchctl print "gui/$(id -u)/$DNS_LABEL" >/dev/null 2>&1; then log_ok "launchd agent $DNS_LABEL loaded"
  else log_error "launchd agent $DNS_LABEL not loaded"; failed=1; fi
  if [[ "$(dig +short +time=2 +tries=1 @127.0.0.1 -p "$DNS_PORT" "probe.$DOMAIN" 2>/dev/null)" == "127.0.0.1" ]]; then log_ok "dnsmasq answers on 127.0.0.1:$DNS_PORT"
  else log_error "dnsmasq does not answer on 127.0.0.1:$DNS_PORT"; failed=1; fi
  for d in "api.$SYSTEM_DOMAIN" "hello.$APPS_DOMAIN" "api.cf.$NIP_DOMAIN"; do
    if resolves_to_loopback "$d"; then log_ok "$d -> 127.0.0.1"
    else log_error "$d does not resolve to 127.0.0.1"; failed=1; fi
  done
  [[ $failed -eq 0 ]] || die "local resolver not fully set up" "run: make dns"
  log_ok "local resolver works (independent of Wi-Fi/internet)"
}

cmd_setup() {
  load_config
  install_agent
  install_resolvers
  cmd_check
}

cmd_remove() {
  load_config
  launchctl bootout "gui/$(id -u)/$DNS_LABEL" >/dev/null 2>&1 || true
  rm -f "$LAUNCH_AGENT" "$CFKD_HOME/dnsmasq.conf"
  log_ok "dnsmasq agent removed"
  local f own=""
  for f in "$RESOLVER_DIR"/*; do is_managed_resolver "$f" && own="$own $f"; done
  if [[ -n "$own" ]]; then
    log_info "removing own resolver files:$own (sudo)"
    # shellcheck disable=SC2086
    sudo rm -f $own
    sudo dscacheutil -flushcache
  fi
  log_ok "local resolver removed"
}

# Every wildcard level needs its own record: existing nodes such as _acme-challenge.sys.<D>
# turn sys.<D> into an "empty non-terminal", and then *.<D> no longer matches api.sys.<D>.
public_dns_records() {
  local -a names
  local n
  read -r -a names <<<"$1"
  for n in "${names[@]}"; do echo "$n."; done
}

cmd_public() {
  load_config
  [[ "$DOMAIN" != "$NIP_DOMAIN" ]] || die "no custom DOMAIN set" "run: make configure DOMAIN=kind.cfapps.cool"
  command -v gcloud >/dev/null || die "gcloud missing" "run: brew install --cask gcloud-cli"
  check_dns >/dev/null
  local zone rec
  gcloud_sa_session
  # shellcheck disable=SC2064
  trap "rm -rf '$CLOUDSDK_CONFIG'" RETURN
  zone="$(gcloud_zone_for "$DOMAIN")"
  [[ -n "$zone" ]] || die "no Cloud DNS zone for $DOMAIN in project $GCP_PROJECT" "check DNS_ZONE/GCP_PROJECT"
  while IFS= read -r rec; do
    if gcloud dns record-sets describe "$rec" --type=A --zone="$zone" --project "$GCP_PROJECT" >/dev/null 2>&1; then
      gcloud dns record-sets update "$rec" --type=A --ttl=300 --rrdatas=127.0.0.1 --zone="$zone" --project "$GCP_PROJECT" >/dev/null
    else
      gcloud dns record-sets create "$rec" --type=A --ttl=300 --rrdatas=127.0.0.1 --zone="$zone" --project "$GCP_PROJECT" >/dev/null
    fi
    log_ok "A $rec -> 127.0.0.1 (zone $zone)"
  done < <(public_dns_records "$CERT_SANS")
}

main() {
  case "${1:-}" in
    public) cmd_public ;;
    setup) cmd_setup ;;
    check) cmd_check ;;
    remove) cmd_remove ;;
    *) die "unknown command '${1:-}'" "usage: scripts/dns.sh setup|check|remove|public" ;;
  esac
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then main "$@"; fi
