#!/usr/bin/env bash
# Web UI (CLAUDE.md chapter 8): Stratos as a native darwin-arm64 binary on the host, served on 127.0.0.1:5443.
#   scripts/ui.sh up        install the pinned release (checksum verified), start the launchd agent, register + connect CF
#   scripts/ui.sh down      stop the agent (data and secrets are kept; called by 'make down')
#   scripts/ui.sh stop      stop and disable: 'make up' no longer starts the UI
#   scripts/ui.sh status    show URL, agent state and endpoint
#   scripts/ui.sh password  print the local admin password
# Secrets (session secret, encryption key, admin password) are generated once per machine and live only in
# ~/.config/cf-kind-demo/stratos/secrets.env (0600). The Stratos config must be ./config.properties in the working directory.
set -euo pipefail

# shellcheck source=tls.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/tls.sh"

STRATOS_VERSION="5.5.3"
STRATOS_SHA256="6ff697a7e93f49ac1aa30bec9e61609c8111b70299b6cb1fcf3dc84fb95518c6"
STRATOS_HOME="$CFKD_HOME/stratos"
STRATOS_LABEL="io.cf-kind-demo.stratos"
STRATOS_AGENT="$HOME/Library/LaunchAgents/$STRATOS_LABEL.plist"
STRATOS_PORT=5443
STRATOS_ENDPOINT_NAME="cf-kind-demo"

stratos_url() { echo "https://ui.$SYSTEM_DOMAIN:$STRATOS_PORT"; }
stratos_asset() { echo "stratos-v${STRATOS_VERSION}-darwin-arm64.tar.gz"; }
stratos_download_url() { echo "https://github.com/cloudfoundry/stratos/releases/download/v${STRATOS_VERSION}/$(stratos_asset)"; }
stratos_release_dir() { echo "$STRATOS_HOME/releases/v$STRATOS_VERSION/stratos-v${STRATOS_VERSION}-darwin-arm64"; }

# Only a publicly trusted certificate (Let's Encrypt prod) lets Stratos verify the CF API strictly
stratos_skip_ssl() {
  if [[ "$DOMAIN" != "$NIP_DOMAIN" && "$TLS_MODE" == "letsencrypt" && "$ACME_ENV" == "prod" ]]; then echo false; else echo true; fi
}

# render_stratos_config CERT KEY UI_PATH SKIP_SSL SESSION_SECRET ENCRYPTION_KEY ADMIN_PASSWORD ORIGIN
render_stratos_config() {
  cat <<EOF
# generated by 'make ui' — do not edit; secrets come from secrets.env
DATABASE_PROVIDER=sqlite
SQLITE_KEEP_DB=true
HTTP_CONNECTION_TIMEOUT_IN_SECS=10
HTTP_CLIENT_TIMEOUT_IN_SECS=30
HTTP_CLIENT_TIMEOUT_MUTATING_IN_SECS=120
HTTP_CLIENT_TIMEOUT_LONGRUNNING_IN_SECS=600
SKIP_SSL_VALIDATION=$4
CONSOLE_PROXY_TLS_ADDRESS=127.0.0.1:$STRATOS_PORT
CONSOLE_PROXY_CERT_PATH=$1
CONSOLE_PROXY_CERT_KEY_PATH=$2
CONSOLE_CLIENT=console
CF_CLIENT=cf
CONSOLE_ADMIN_SCOPE=stratos.admin
CF_ADMIN_ROLE=cloud_controller.admin
ALLOWED_ORIGINS=$8
SESSION_STORE_SECRET=$5
ENCRYPTION_KEY=$6
UI_PATH=$3
LOG_TO_JSON=false
LOG_API_REQUESTS=false
SSO_LOGIN=false
USER_ENDPOINTS_ENABLED=disabled
AUTH_ENDPOINT_TYPE=local
LOCAL_USER=admin
LOCAL_USER_PASSWORD=$7
LOCAL_USER_SCOPE=stratos.admin
EOF
}

render_stratos_plist() {
  local bin="$1" dir="$2" log="$3"
  cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$STRATOS_LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$bin</string>
  </array>
  <key>WorkingDirectory</key>
  <string>$dir</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>$log</string>
  <key>StandardErrorPath</key>
  <string>$log</string>
</dict>
</plist>
EOF
}

# xsrf_from_headers < HTTP response headers — Stratos returns the XSRF token with the login response
xsrf_from_headers() {
  awk -F': *' 'tolower($1)=="x-xsrf-token" {gsub(/\r/, "", $2); print $2; exit}'
}

endpoint_guid_by_name() {
  jq -r --arg n "$1" '.[]? | select(.name == $n) | .guid' | head -1
}

ensure_stratos_secrets() {
  mkdir -p "$STRATOS_HOME"
  chmod 700 "$STRATOS_HOME"
  [[ -s "$STRATOS_HOME/secrets.env" ]] && return 0
  (
    umask 077
    printf 'SESSION_STORE_SECRET=%s\nENCRYPTION_KEY=%s\nADMIN_PASSWORD=%s\n' \
      "$(openssl rand -hex 32)" "$(openssl rand -hex 32 | tr 'a-f' 'A-F')" "$(openssl rand -hex 12)" > "$STRATOS_HOME/secrets.env"
  )
}

# stratos_cert_paths -> "<fullchain> <key>" matching the demo domain
stratos_cert_paths() {
  if needs_public_tls; then
    local src; src="$(gateway_cert_source)"
    echo "$src/fullchain.pem $src/privkey.pem"
  else
    echo "$UPSTREAM_DIR/temp/certs/all-in-one.crt $UPSTREAM_DIR/temp/certs/all-in-one.key"
  fi
}

install_stratos() {
  local dir; dir="$(stratos_release_dir)"
  [[ -x "$dir/bin/jetstream" ]] && return 0
  [[ "$AIRGAP" == "true" ]] && die "Stratos v$STRATOS_VERSION is not installed and AIRGAP=true" "install it once while online: make ui"
  local tmp; tmp="$(mktemp -d)"
  log_info "downloading Stratos v$STRATOS_VERSION (darwin-arm64)"
  curl -fsSL -o "$tmp/$(stratos_asset)" "$(stratos_download_url)" || { rm -rf "$tmp"; die "download failed" "check the internet connection"; }
  echo "$STRATOS_SHA256  $tmp/$(stratos_asset)" | shasum -a 256 -c - >/dev/null \
    || { rm -rf "$tmp"; die "checksum mismatch for $(stratos_asset)" "do not use this download; check STRATOS_SHA256"; }
  mkdir -p "$STRATOS_HOME/releases/v$STRATOS_VERSION"
  tar -xzf "$tmp/$(stratos_asset)" -C "$STRATOS_HOME/releases/v$STRATOS_VERSION"
  rm -rf "$tmp"
  log_ok "Stratos v$STRATOS_VERSION installed (checksum verified)"
}

start_stratos() {
  local run="$STRATOS_HOME/run" cert key
  mkdir -p "$run" "$CFKD_HOME/logs"
  read -r cert key <<<"$(stratos_cert_paths)"
  [[ -s "$cert" && -s "$key" ]] || die "no certificate for $(stratos_url)" "run: make up (and make certs for Let's Encrypt)"
  # shellcheck source=/dev/null
  source "$STRATOS_HOME/secrets.env"
  (umask 077; render_stratos_config "$cert" "$key" "$(stratos_release_dir)/ui" "$(stratos_skip_ssl)" \
    "$SESSION_STORE_SECRET" "$ENCRYPTION_KEY" "$ADMIN_PASSWORD" "$(stratos_url)" > "$run/config.properties")
  render_stratos_plist "$(stratos_release_dir)/bin/jetstream" "$run" "$CFKD_HOME/logs/stratos.log" > "$STRATOS_AGENT"
  launchctl bootout "gui/$(id -u)/$STRATOS_LABEL" >/dev/null 2>&1 || true
  launchctl bootstrap "gui/$(id -u)" "$STRATOS_AGENT"
  local i
  for ((i = 0; i < 30; i++)); do
    curl -sf --max-time 2 --resolve "ui.$SYSTEM_DOMAIN:$STRATOS_PORT:127.0.0.1" -k "$(stratos_url)/pp/v1/ping" >/dev/null && { log_ok "Stratos running: $(stratos_url)"; return 0; }
    sleep 1
  done
  die "Stratos did not start" "see $CFKD_HOME/logs/stratos.log"
}

# Register the CF endpoint (once) and connect it with the ccadmin credentials (every run: tokens change on redeploy)
connect_endpoint() {
  local url jar hdr xsrf guid pwfile
  url="$(stratos_url)"
  jar="$(mktemp)" pwfile="$(mktemp)"
  # shellcheck disable=SC2064
  trap "rm -f '$jar' '$pwfile'" RETURN
  local curl_opts=(-s --resolve "ui.$SYSTEM_DOMAIN:$STRATOS_PORT:127.0.0.1" -b "$jar" -c "$jar")
  [[ "$(stratos_skip_ssl)" == "true" ]] && curl_opts+=(-k)
  # shellcheck source=/dev/null
  source "$STRATOS_HOME/secrets.env"
  hdr="$(curl "${curl_opts[@]}" -D - -o /dev/null -X POST --data-urlencode "username=admin" --data-urlencode "password=$ADMIN_PASSWORD" "$url/pp/v1/auth/login/uaa")"
  xsrf="$(xsrf_from_headers <<<"$hdr")"
  [[ -n "$xsrf" ]] || die "Stratos login failed" "see $CFKD_HOME/logs/stratos.log"
  guid="$(curl "${curl_opts[@]}" "$url/api/v1/endpoints" | endpoint_guid_by_name "$STRATOS_ENDPOINT_NAME")"
  if [[ -z "$guid" ]]; then
    guid="$(curl "${curl_opts[@]}" -H "X-XSRF-Token: $xsrf" -X POST --data-urlencode "cnsi_name=$STRATOS_ENDPOINT_NAME" \
      --data-urlencode "api_endpoint=https://api.$SYSTEM_DOMAIN" --data-urlencode "skip_ssl_validation=$(stratos_skip_ssl)" \
      --data-urlencode "endpoint_type=cf" "$url/api/v1/endpoints" | jq -r '.guid // empty')"
    [[ -n "$guid" ]] || die "could not register the CF endpoint in Stratos" "is the CF API up? make status"
    log_ok "CF endpoint registered in Stratos: $STRATOS_ENDPOINT_NAME"
  fi
  local secrets="$UPSTREAM_DIR/temp/secrets.sh"
  [[ -f "$secrets" ]] || die "$secrets missing — is Cloud Foundry installed?" "run: make up"
  (umask 077; bash -c 'source "$1"; printf %s "$CC_ADMIN_PASSWORD"' _ "$secrets" > "$pwfile")
  if curl "${curl_opts[@]}" -H "X-XSRF-Token: $xsrf" -X POST --data-urlencode "cnsi_guid=$guid" --data-urlencode "connect_type=creds" \
    --data-urlencode "username=ccadmin" --data-urlencode "password@$pwfile" "$url/api/v1/tokens" | jq -e '.admin == true' >/dev/null; then
    log_ok "Stratos connected to https://api.$SYSTEM_DOMAIN as ccadmin (admin)"
  else
    die "could not connect Stratos to the CF endpoint" "see $CFKD_HOME/logs/stratos.log"
  fi
}

cmd_up() {
  install_stratos
  ensure_stratos_secrets
  start_stratos
  connect_endpoint
  touch "$STRATOS_HOME/enabled"
  log_ok "open $(stratos_url) — user: admin, password: make ui-password"
}

cmd_down() {
  if launchctl print "gui/$(id -u)/$STRATOS_LABEL" >/dev/null 2>&1; then
    launchctl bootout "gui/$(id -u)/$STRATOS_LABEL" >/dev/null 2>&1 || true
    log_ok "Stratos stopped (data and secrets kept in $STRATOS_HOME)"
  fi
  rm -f "$STRATOS_AGENT"
}

cmd_status() {
  printf 'URL:      %s\nVersion:  v%s\nAgent:    %s\n' "$(stratos_url)" "$STRATOS_VERSION" \
    "$(launchctl print "gui/$(id -u)/$STRATOS_LABEL" >/dev/null 2>&1 && echo running || echo stopped)"
}

main() {
  load_config
  case "${1:-}" in
    up) cmd_up ;;
    down) cmd_down ;;
    status) cmd_status ;;
    stop) cmd_down; rm -f "$STRATOS_HOME/enabled"; log_ok "web UI disabled (make ui enables it again)" ;;
    password) ensure_stratos_secrets; sed -n 's/^ADMIN_PASSWORD=//p' "$STRATOS_HOME/secrets.env" ;;
    *) die "unknown command '${1:-}'" "usage: scripts/ui.sh up|down|stop|status|password" ;;
  esac
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then main "$@"; fi
